[package]
name = "ck-launcher"
version = "0.1.62-beta.1"
description = "Windows launcher for licensed Minecraft: Java Edition"
license = "AGPL-3.0-only"
authors = ["CK Launcher"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ck-launcher-core = { path = "../../crates/launcher-core" }
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
serde_json = "1"
windows-sys = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging"] }
winreg = "0.55"
