[package]
name = "ck-launcher"
version = "1.0.0"
description = "Kvanth Launcher for Minecraft: Java Edition on Windows 10 and 11"
license = "AGPL-3.0-only"
authors = ["Kvanth"]
edition = "2021"
autobins = false

[[bin]]
name = "kvanth-launcher"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
ck-launcher-core = { path = "../../crates/launcher-core" }
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
serde_json = "1"
windows-sys = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging"] }
winreg = "0.55"
